stages:
  - build
  - deploy
  - deploy_to_server

variables:
  SERVICE_PORT: "9400"
  VERSION: "0.1.0"

cache:
  paths:
   - node_modules/

build_job:
  stage: build
  script:
    - rm -rf dist docker/dist
    - yarn
    - yarn run build
    - mv dist docker
    - cd docker
    - PUBLISH_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d'/' -f 2)
    - docker build --build-arg PUBLISH_VERSION=$PUBLISH_VERSION -t registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:$DOCKER_IMAGE_VERSION .
  tags:
    - Dev

deploy_job:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - PUBLISH_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d'/' -f 2)
    - docker stop nginx-htouhui-front-$CI_BUILD_REF_SLUG || true
    - docker rm -f nginx-htouhui-front-$CI_BUILD_REF_SLUG || true
    - docker run -d -p $SERVICE_PORT:80 --name nginx-htouhui-front-$CI_BUILD_REF_SLUG -t registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:$DOCKER_IMAGE_VERSION
  tags:
    - Dev

deploy_docker_image:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: http://loan.htouhui.com/
  when: manual
  script:
    - DATE=`date +%Y%m%d`
    - DOCKER_IMAGE_VERSION=$VERSION-$DATE-$CI_PIPELINE_ID
    - docker login --username=228044108@qq.com --password=cnFbU8VKtvn3daF registry-internal.cn-beijing.aliyuncs.com
    - docker tag registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:$DOCKER_IMAGE_VERSION registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:latest
    - docker push registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:$DOCKER_IMAGE_VERSION
    - docker push registry-internal.cn-beijing.aliyuncs.com/htouhui/nginx-htouhui-front:latest
  tags:
    - Dev
